/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-05-02 03:54:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/GitHub/Spring/workspace-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cns/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1549971507233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"/resources/css/modern-business.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/resources/css/ij-css.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>QuadCore News</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg navbar-dark fixed-top\"\r\n");
      out.write("\t\tstyle=\"background-color: #A566FF\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"news_index.do\">QuadCore News</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\t<div class=\"container\" style=\"padding-top: 30px;\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow\"\r\n");
      out.write("\t\t\tstyle=\"background-color: #343a40\">\r\n");
      out.write("\t\t\t<img class=\"mr-3\" src=\"img/user.png\" alt=\"\" width=\"48\" height=\"48\">\r\n");
      out.write("\t\t\t<div class=\"lh-100\">\r\n");
      out.write("\t\t\t\t<h6 class=\"mb-0 text-white lh-100\">MyPage</h6>\r\n");
      out.write("\t\t\t\t<small>test@test.com</small>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"my-3 p-3 bg-white rounded box-shadow\">\r\n");
      out.write("\t\t\t<h6 class=\"border-bottom border-gray pb-2 mb-0\">내가 스크랩한 뉴스</h6>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">여야, 손혜원 논란 이어 조해주\r\n");
      out.write("\t\t\t\t\t\t임명 놓고 공방…정국 '꽁꽁'</strong> 한국당, 문대통령 조해주 임명 강행에 의사일정 보이콧 선언\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=e83e8c&fg=e83e8c&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">원시 지구, 행성과 대충돌로 생명체\r\n");
      out.write("\t\t\t\t\t\t원소 받았다</strong> 과연 지구의 생명체는 최초 어떻게 생겨날 수 있었을까?\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=6f42c1&fg=6f42c1&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">'뚱카롱' 열풍…\"기형적 마카롱\"\r\n");
      out.write("\t\t\t\t\t\tvs \"한국적 재해석\"</strong> 뚱카롱은 '뚱뚱한 마카롱'을 줄인 신조어. '꼬끄(coque)'라고 부르는 마카롱 껍질 사이에\r\n");
      out.write("\t\t\t\t\t필링을 두텁게 채워 넣은 형태를 말한다.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<small class=\"d-block text-right mt-3\"> <a href=\"#\">더보기</a>\r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"my-3 p-3 bg-white rounded box-shadow\">\r\n");
      out.write("\t\t\t<h6 class=\"border-bottom border-gray pb-2 mb-0\">나의 태그</h6>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">좋아하는 태그</strong> <span>#취업</span>\r\n");
      out.write("\t\t\t\t\t<span>#취업</span> <span>#취업</span> <span>#취업</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">좋아하는 태그</strong> <span>#취업</span>\r\n");
      out.write("\t\t\t\t\t<span>#취업</span> <span>#취업</span> <span>#취업</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<small class=\"d-block text-right mt-3\"> <a href=\"#\">수정하기</a>\r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"my-3 p-3 bg-white rounded box-shadow\">\r\n");
      out.write("\t\t\t<h6 class=\"border-bottom border-gray pb-2 mb-0\">회원정보</h6>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">이름</strong> 김**\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=e83e8c&fg=e83e8c&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">생년월일</strong> ****년 **월 **일\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"media text-muted pt-3\">\r\n");
      out.write("\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\tdata-src=\"holder.js/32x32?theme=thumb&bg=6f42c1&fg=6f42c1&size=1\"\r\n");
      out.write("\t\t\t\t\talt=\"\" class=\"mr-2 rounded\">\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tclass=\"media-body pb-3 mb-0 small lh-125 border-bottom border-gray\">\r\n");
      out.write("\t\t\t\t\t<strong class=\"d-block text-gray-dark\">주소</strong> 서울특별시 도봉구 삼양로144\r\n");
      out.write("\t\t\t\t\t33길\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<small class=\"d-block text-right mt-3\"> <a href=\"#\">수정하기</a>\r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
