/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-05-02 05:28:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class news_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/GitHub/Spring/workspace-sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cns/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1549971507233L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"/resources/css/modern-business.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/resources/css/ij-css.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>QuadCore News</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg navbar-dark fixed-top\"\r\n");
      out.write("\t\tstyle=\"background-color: #A566FF\">\r\n");
      out.write("\t\t<!--  bg-dark -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"news_index.do\">QuadCore\r\n");
      out.write("\t\t\t\tNews</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarResponsive\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"news_index.do\">Home</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t카테고리 </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item active\" href=\"politics.do\">정치</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"economy.do\">경제</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"society.do\">사회</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"living.do\">생활문화</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"itSicence.do\">IT과학</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tid=\"navbarDropdownPortfolio\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> 타임라인 </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownPortfolio\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"tag.do\">#취업</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"tag.do\">#미국</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"tag.do\">#스카이캐슬</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownBlog\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t신문사 </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\"\r\n");
      out.write("\t\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"category/chosun.do\">조선일보</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"category/donga.do\">동아일보</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"category/hankyoreh.do\">한겨례</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"category/joongang.do\">중앙일보</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"category/yonhap.do\">연합뉴스</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page Heading/Breadcrumbs -->\r\n");
      out.write("\t\t<img style=\"float: right\"\r\n");
      out.write("\t\t\tsrc=\"https://mimgnews.pstatic.net/image/upload/office_logo/003/2018/01/24/logo_003_38_20180124113224.png\"\r\n");
      out.write("\t\t\talt=\"신문사로고\">\r\n");
      out.write("\t\t<h2 class=\"mt-4 mb-3\">\r\n");
      out.write("\t\t\t<b>日초계기 위협비행 사진 본 항해사들…\"해적이나 하는 행위\"</b> <br /> <small>\"대조영함\r\n");
      out.write("\t\t\t\t레이더 정보 데이터 정확할 것\"</small>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t<li class=\"breadcrumb-item active\">기사입력 2019-01-25 12:56 최종수정\r\n");
      out.write("\t\t\t\t2019-01-25 14:16</li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Blog Entries Column -->\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Blog Post -->\r\n");
      out.write("\t\t\t\t<div class=\"card mb-4\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc='https://imgnews.pstatic.net/image/003/2019/01/25/NISI20190124_0014840418_web_20190124181543_20190125141607132.jpg?type=w647'>\r\n");
      out.write("\t\t\t\t\t<p style=\"margin: 5px 10px 20px 20px\">\r\n");
      out.write("\t\t\t\t\t\t<small>【서울=뉴시스】국방부는 24일 일본 해상초계기의 근접 위협비행 모습을 촬영한 영상을\r\n");
      out.write("\t\t\t\t\t\t\t공개했다. 전날 오후 2시3분께 이어도 서남방 131㎞ 떨어진 공해상에서 정상적인 작전 활동을 펼치던 해군 구축함\r\n");
      out.write("\t\t\t\t\t\t\t대조영함을 향해 일본 P-3 초계기가 540m까지 접근했으며 해수면에서 60~70m 높이로 초저고도 비행을 했다.\r\n");
      out.write("\t\t\t\t\t\t\t2019.01.24. (사진=국방부 제공) photo@newsis.com</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<pre>\r\n");
      out.write("\t\t\t\t\t\t\t\t<b>\r\n");
      out.write("  \"대조영함 레이더 정보 데이터 정확할 것\"\r\n");
      out.write("  \"일반상선끼리 통항해도 1마일 거리유지\"\r\n");
      out.write("  \"분쟁 지역서 미군도 이렇게는 비행 안해\"\r\n");
      out.write("  \"조타실서 보면 바로 머리 위나 마찬가지\"\r\n");
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t</pre>\r\n");
      out.write("\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t<pre>\r\n");
      out.write("  【서울=뉴시스】김성진 기자 = \"해적들이 하는 행위나 다를 바 없어 보이네요.\"\r\n");
      out.write("\r\n");
      out.write("  군 당국이 전날인 24일 공개한 일본 P-3 해상초계기의 저공 위협 비행 사진과 레이더 정보를 본\r\n");
      out.write("  항해사 이모(32)씨의 첫마디다. 연중 육지보다 바다에서 시간을 더 많이 보내는 선상 근무자들은\r\n");
      out.write("  하나같이 일본 초계기의 저공 위협 비행에 대해 비판의 목소리를 냈다.\r\n");
      out.write("\r\n");
      out.write("  대형 상선 회사에서 10년차 1등 항해사로 근무하고 있는 이모(32)씨는 초계기 사진을 곰곰이\r\n");
      out.write("  지켜보고는 \"대조영함 레이더에 다 잡혔다\"며 \"데이터가 정확할 것\"이라고 밝혔다.\r\n");
      out.write("\r\n");
      out.write("  이씨는 그러면서 \"일반 상선끼리 통항할 때도 1마일(1해리·1.852㎞)을 지킨다\"며 \"군용 비행기가\r\n");
      out.write("  저렇게 넓은 곳에서 비행을 했다면 도발이 맞다\"고 지적했다.\r\n");
      out.write("\r\n");
      out.write("  군 당국에 따르면 앞서 지난 23일 해군 구축함 대조영함은 이어도 서남쪽 131㎞ 지점 바다\r\n");
      out.write("  한가운데에서 정상적인 작전활동을 수행 중이었다. 이 해역은 한국·중국·일본 방공식별구역이\r\n");
      out.write("  중첩되지만 우리의 배타적경제수역(EEZ)에 해당한다.\r\n");
      out.write("\r\n");
      out.write("  일본 초계기는 대조영함이 \"귀국은 우리 쪽으로 접근하고 있다. 경로를 이탈하라\", \"더 이상\r\n");
      out.write("  접근하면 자위권적인 조치를 취하겠다\"고 20여 차례나 통신을 시도했지만 응답하지 않았다.\r\n");
      out.write("\r\n");
      out.write("  이후 초계기는 오후 2시3분께 고도 60~70m에서 불과 540m만 떨어져 대조영함을 지나갔고, 이 같은\r\n");
      out.write("  모습은 대조영함의 레이더뿐만 아니라 열영상장비와 캠코더 등이 포착한 영상 등에도 고스란히 담겼다\r\n");
      out.write("\r\n");
      out.write("  미 항공모함의 전투기가 쉴 새 없이 날아다니는 중동 호르무즈 해협을 수차례 넘나든 경험이 있는\r\n");
      out.write("  이씨는 \"미군도 이렇게까지는 하지 않는다\"며 \"전투기가 (일본 위협 비행 거리보다) 더 멀리\r\n");
      out.write("  지나다녀도 그 소음과 진동은 굉장하다. 배에서는 불안감을 느낄 수밖에 없다\"고 목소리를 높였다.\r\n");
      out.write("\r\n");
      out.write("  대형 상선에서 선장으로 근무하고 있는 신모(44)씨도 마찬가지 입장을 표명했다. 신씨는 \"상선과\r\n");
      out.write("  군함의 임무가 다르기 때문에 정서상 받아들이는 차이는 있겠다\"면서도 \"고도 60~70m는\r\n");
      out.write("  브리지(bridge·조타실)를 기준으로 하면 바로 머리 위나 마찬가지\"라고 지적했다.\r\n");
      out.write("\r\n");
      out.write("  신씨는 \"(일본 초계기가 최근접한) 0.3마일이면 약 500여m거리인데 비행기의 속도로 봐서 근접\r\n");
      out.write("  상황일 때 훨씬 더 위협이 느껴졌을 것이라는 생각이 든다\"며 \"더군다나 비행기 엔진음은 배보다\r\n");
      out.write("  훨씬 크기 때문에 체감하는 긴장도는 훨씬 크다고 보인다\"고 말했다.\r\n");
      out.write("              </pre>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--div class=\"card-footer text-muted\">\r\n");
      out.write("\r\n");
      out.write("            </div-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Pagination -->\r\n");
      out.write("\t\t\t\t<ul class=\"pagination justify-content-center mb-4\">\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&larr;\r\n");
      out.write("\t\t\t\t\t\t\tOlder</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Newer\r\n");
      out.write("\t\t\t\t\t\t\t&rarr;</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar Widgets Column -->\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Search Widget >\r\n");
      out.write("          <div class=\"card mb-4\">\r\n");
      out.write("            <h5 class=\"card-header\">Search</h5>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                <span class=\"input-group-btn\">\r\n");
      out.write("                  <button class=\"btn btn-secondary\" type=\"button\">Go!</button>\r\n");
      out.write("                </span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Categories Widget -->\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<!-- my-4 -->\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t<b>관련 기사</b>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- col-lg-6 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"mb-0 list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--list-unstyled -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li style=\"margin: 0px 0px 5px 5px;\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13px\">日, 초계기 저공비행 반박에…軍 \"日 상응 자료 내놔야\"</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li style=\"margin: 0px 0px 5px 5px;\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13px\">日방위상, 초계기 위협비행 \"반박 증거 제시할 생각 없다\"</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li style=\"margin: 0px 0px 5px 5px;\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 13px\">국방부 “초계기 논란, 이제 일본이 상응하는 자료 내놔야” </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Side Widget -->\r\n");
      out.write("\t\t\t\t<div class=\"card my-4\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-header\">태그 Tags</h5>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\">日초계기</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\">日위협비행</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\">대조영함</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\">日저공비행</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"py-5 bg-dark\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\tWebsite 2018</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t<script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"/resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
